### ISSUE TITLE
Did Source Code Move Elsewhere? Is it Still Available?

### ISSUE THREAD

**Issue by davidshq** [ServerPress/DesktopServer#6]
Just getting used to DesktopServer. Noticed this repo but it hasn't been edited in quite a while. Did you guys go to using a private repo for DesktopServer or is it hosted somewhere else?

**Comment by davejesch** [comment]
@davidshq This repository is for the DesktopServer *plugin* which can be found in the WordPress Plugin Repository here: https://wordpress.org/plugins/desktopserver/ - this is used by the DesktopServer application when deploying web sites. It is still used by the current version of DesktopServer but has not required any changes for quite some time.

The DesktopServer application is in a separate, private repository.

**Comment by davidshq** [comment]
Thanks Dave!
